language: java
jdk: oraclejdk8
sudo: required
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --only-upgrade -y oracle-java8-installer
before_script: javac -version
script: ant -f JALSE/build.xml
