language: java
jdk: oraclejdk8
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --only-upgrade -y oracle-java8-installer
  - echo `javac -version`
script: ant -f JALSE/build.xml
